# shorten.http
# Test creating short URLs

### Shorten a valid URL
POST http://localhost:8081/v1/shorten
Content-Type: application/json

{
  "long_url": "https://www.example.com/"
}

### Shorten another valid URL
POST http://localhost:8081/v1/shorten
Content-Type: application/json

{
  "long_url": "https://github.com"
}

### Invalid URL (expecting 400 Bad Request)
POST http://localhost:8081/v1/shorten
Content-Type: application/json

{
  "long_url": "not-a-valid-url"
}

### Missing URL fieldbud field (expecting 400 Bad Request)
POST http://localhost:8081/v1/shorten
Content-Type: application/json

{}

### Get Example element in database json file
GET http://localhost:8081/v1/1276058